### GENERAL SETTINGS ###

# Site settings
title: Ebony Xscape
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: UA-50546869-2
baseurl: "/home" #important: start with /
url: "http://ebonyxscape.github.io/home/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#198c19" #"#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#73481d" #"#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#73481d" #"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCrbJDDPfYpXJwSjoP-cnhBQ?view_as=public
  - title: facebook
    url: https://www.facebook.com/jessica.mack.969
  - title: twitter
    url: https://twitter.com/EbonyXscape
  - title: instagram
    url: https://www.instagram.com/ebonyxscape/
#  - title: tumblr
 #   url: https://www.tumblr.com/blog/ebonyxscape
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
#  - lines: 
 #   - Some Ave, 987,
  #  - 23890, New York,
   # - United States.
email: ebonyxscape@gmail.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
#members:
 # - name: Mark Webber
 #   position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
 #   img: team01.jpg
  #  social:
   #   - title: envelope #use for email address
    #    url: mailto:name@domain.com
     # - title: twitter
      #  url: http://twitter.com/handle
      #Just keep cipying and adding people as needed.
 
    
# Clients information. Shown on Home and About pages.
#clients:
 # - name: dribbble
#    img: client01.png
#  - name: Code is Poetry
#    img: client02.png
#  - name: Vimeo
#    img: client03.png
#  - name: VimeoPro
#    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page. 
#testimonial:
    message: "I have always believed that there is power in the arts and STEM, but there are so many possibilities when there is collaboration between the two. I hope to share important information about creators in the arts and/or technology, as well as my own artistsic endeavors. This is a world of unconventionally colored creators."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
